# Generated by Django 4.0.6 on 2022-07-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='description',
        ),
        migrations.RemoveField(
            model_name='items',
            name='status',
        ),
    ]
